DROP TABLE IF EXISTS public.extensions CASCADE;
CREATE TABLE public.extensions (
    id SERIAL PRIMARY KEY,
    num INTEGER NOT NULL,
    pr TEXT,
    cat TEXT NOT NULL,
    t_ar TEXT NOT NULL,
    t_en TEXT,
    ref BOOLEAN,
    desc_text TEXT,
    link TEXT,
    subs JSONB,
    icon TEXT,
    downloads INTEGER NOT NULL DEFAULT 0
);

TRUNCATE TABLE public.extensions;
ALTER TABLE public.extensions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Extensions" ON public.extensions;

CREATE POLICY "Public Read Extensions" ON public.extensions
    FOR SELECT TO anon, authenticated
    USING (true);

GRANT SELECT ON public.extensions TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.increment_extension_download(p_id integer)
RETURNS void AS $$
BEGIN
    UPDATE public.extensions
    SET downloads = COALESCE(downloads, 0) + 1
    WHERE id = p_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION public.increment_extension_download(integer) TO anon, authenticated;

INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (1, 'P', 'اساسيات', 'اعتماد النظام الموحد للتصميم (Platforms Code) إصدار 1.0 بشكل صحيح', 'Unified Design System v1.0 correctly implemented', true, 'التأكد من تطبيق النسخة 1.0 من نظام التصميم الموحد (كود المنصات) بشكل صحيح على المنصة', 'https://design.dga.gov.sa/', '["التأكد من استيراد مكتبة كود المنصات بنسختها الصحيحة 1.0","مراجعة جميع المكونات للتحقق من توافقها مع الإصدار الحالي"]', 'dashboard');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (2, 'P', 'اساسيات', 'استخدام الألوان المعتمدة وفق نظام التصميم الموحد', 'Use of approved color tokens', true, 'الالتزام باستخدام رموز ألوان التصميم (Color Design Tokens) دون تعديل أو استبدال', 'https://design.dga.gov.sa/guidelines/foundations/color-system', '["الالتزام باستخدام رموز ألوان التصميم مثل الألوان المخصصة للخلفيات والخطوط وغيرها","في حال إضافة عناصر على خلفيات ملونة يجب التحقق من تحقيق متطلبات التباين والوضوح","استخدام خاصية On Color الموجودة في العناصر لضمان إمكانية الوصول"]', 'palette');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (3, 'P', 'اساسيات', 'الالتزام بإرشادات الطباعة من حيث الخطوط والأوزان والمقاسات المتجاوبة', 'Typography — fonts, weights, responsive scale', true, 'الالتزام باستخدام الخط المعتمد IBM Plex Sans Arabic مع تطبيق متغيرات الخط الصحيحة', 'https://design.dga.gov.sa/guidelines/foundations/typography', '["استخدام الخط المعتمد IBM Plex Sans Arabic كما هو محدد في كود المنصات","تطبيق متغيرات الخط الصحيحة حسب رموز خطوط التصميم (Display variants)","تطبيق متغيرات النصوص (Text variants) بشكل صحيح"]', 'type');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (4, 'P', 'اساسيات', 'تطبيق قيم المسافات وفق نظام التصميم الموحد', 'Spacing tokens applied per system', true, 'الالتزام بوحدات القياس المعتمدة في كود المنصات مثل 4px و8px و16px', 'https://design.dga.gov.sa/guidelines/foundations/layout-and-spacing', '["الالتزام بوحدات القياس المعتمدة (4px، 8px، 16px...) عند تحديد المسافات","استخدام رموز المسافات (Global Spacing Design Tokens) فقط","عدم استخدام المسافات المخصصة للعناصر"]', 'spacing');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (5, 'P', 'اساسيات', 'تصميم متجاوب يتكيف مع مختلف الأجهزة والاتجاهات', 'Responsive design across devices and orientations', true, 'التأكد من أن التصميم يتكيف مع أحجام الشاشات المختلفة لتوفير تجربة سلسة عبر الأجهزة', 'https://design.dga.gov.sa/guidelines/foundations/layout-and-spacing', '["التصميم متجاوب ويعيد ترتيب الأعمدة والمكونات تلقائياً حسب حجم الشاشة (Mobile, Tablet, Desktop)","التأكد من أن التطبيق/الموقع قابل للاستخدام الكامل على الأجهزة المحمولة","مراعاة تفاعلات اللمس وحجم إطار العرض والوصول إلى التنقل على الشاشات الصغيرة"]', 'mobile');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (6, 'P', 'اساسيات', 'استخدام الأيقونات المعتمدة وفق نظام التصميم الموحد', 'Approved iconography (PC 1.0 Icons)', true, 'الالتزام باستخدام مكتبة الأيقونات في كود المنصات دون استبدال أو تعديل في الحجم أو اللون', 'https://design.dga.gov.sa/guidelines/foundations/iconography', '["استخدام مكتبة الأيقونات الرسمية فقط دون أي تغييرات في الحجم أو اللون","للاستخدامات التنبيهية: استخدام الأيقونات ذات الألوان التنبيهية المعتمدة حصراً","للاستخدامات العامة: استخدام أيقونات بألوان محايدة أو أساسية","لأيقونات أكبر من 24px: استخدام Featured icon دون تعديل"]', 'icons');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (7, 'P', 'قوالب', 'تطبيق قالب الصفحة الرئيسية وفق نوع المنصة', 'Homepage template applied per platform', true, 'تطبيق قالب الصفحة الرئيسية بما يتناسب مع نوع المنصة (معلوماتية أو خدماتية)', 'https://design.dga.gov.sa/guidelines/templates/home-page', '["الالتزام بالقسم الرئيسي واستخدام أحد أنواعه المعتمدة (صورة، خلفية لونية، أو كائن)","للمنصات المعلوماتية: قسم الأخبار أول قسم بعد القسم الرئيسي","للمنصات الخدماتية: قسم الخدمات أول قسم بعد القسم الرئيسي","للأقسام الجديدة: الالتزام باستخدام الأساسات والعناصر المعتمدة"]', 'home');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (8, 'P', 'قوالب', 'تطبيق قالب صفحة الخدمة', 'Service page template applied', true, 'الالتزام الكامل بقالب صفحة الخدمة المعتمد بما يشمل المصطلحات والعناوين', 'https://design.dga.gov.sa/guidelines/templates/service-page', '["استخدام نفس المصطلحات والعناوين: الخطوات، الشروط، المستندات المطلوبة، بطاقة تفاصيل الخدمة","تطبيق عنصر التقييم بجميع مكوناته كما هو معتمد دون تعديل","تطبيق عنصر التغذية الراجعة بجميع مكوناته كما هو معتمد دون تعديل"]', 'file');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (9, 'P', 'قوالب', 'تطبيق قالب المشاركة الإلكترونية', 'e-Participation template applied', true, 'الالتزام بقالب الصفحة الرئيسية للمشاركة الإلكترونية بالأقسام الـ8 كما هي', 'https://design.dga.gov.sa/guidelines/templates/e-participation-page', '["الالتزام بقالب الصفحة الرئيسية للمشاركة الإلكترونية بالأقسام الـ8 كاملة","في حال عدم وجود صفحات فرعية، يمكن استخدام الروابط الموجودة في الأقسام"]', 'users');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (10, 'P', 'قوالب', 'تطبيق قالب البحث', 'Search template applied', true, 'الالتزام بقالب البحث من مكتبة كود المنصات مع ضمان فعالية وظيفة البحث', 'https://design.dga.gov.sa/guidelines/templates/search-page', '["الالتزام بقالب البحث كما هو موجود في مكتبة كود المنصات في Figma","توفر شريط البحث في صفحة النتائج","فعالية وكفاءة وظيفة البحث (ملاءمة النتائج وسرعتها)","عرض النتائج بشكل منظم حسب التصنيفات المعتمدة مع إمكانية الفلترة"]', 'search');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (11, 'P', 'عناصر', 'الختم الرقمي يتبع نظام التصميم الموحد', 'Digital stamp follows PC Design System', true, 'ضمان توافق عنصر الختم الرقمي مع معايير التصميم الموحد وربطه بصفحة الشهادة', 'https://design.dga.gov.sa/guidelines/components/content-display/digital-stamp', '["وضع الختم في أعلى الصفحة","التأكد من ربط رقم الشهادة بالصفحة الخاصة بها بشكل صحيح","يمكن إضافة عناصر ثانوية على الجانب الأيسر بحد أقصى عنصرين"]', 'certificate');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (13, 'P', 'عناصر', 'حقل القائمة المنسدلة يتبع النظام', 'Dropdown input follows PC Design System', true, 'ضمان توافق القائمة المنسدلة مع معايير التصميم الموحد مع حالاتها التفاعلية', 'https://design.dga.gov.sa/guidelines/components/actions/dropdown', '["استخدام العنصر كما هو معتمد دون تعديل إلا لزيادة عناصر خيارات القائمة","تطبيق الحالات: Default, Hovered, Pressed, Focused, Read-only, Disabled"]', 'dropdown');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (14, 'P', 'عناصر', 'الرابط يتبع نظام التصميم الموحد', 'Link follows PC Design System', true, 'التحقق من أن عنصر الرابط يتماشى مع نظام التصميم مع إضافة أيقونة للروابط الخارجية', 'https://design.dga.gov.sa/guidelines/components/actions/link', '["استخدام الرابط كما هو معتمد دون تعديل على التصميم الأساسي","تطبيق الحالات: Default, Hovered, Pressed, Focused, Visited, Disabled","في حال وجود رابط خارجي يجب إضافة أيقونة External link"]', 'link');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (15, 'P', 'عناصر', 'الأكورديون يتبع نظام التصميم الموحد', 'Accordions follow PC Design System', true, 'التأكد من استخدام الأكورديون وفقاً لمبادئ التصميم الموحد مع حالاته الكاملة', 'https://design.dga.gov.sa/guidelines/components/content-display/accordion', '["استخدام العنصر كما هو معتمد دون تعديل على التصميم الأساسي","تطبيق الحالات التفاعلية: Default, Hovered, Pressed, Focused, Disabled","تطبيق الحالات السياقية: Expanded / Collapsed"]', 'accordion');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (16, 'P', 'عناصر', 'القائمة تتبع نظام التصميم الموحد', 'Menu follows PC Design System', true, 'ضمان توافق عنصر القائمة مع إرشادات التصميم الموحد وحالاته التفاعلية', 'https://design.dga.gov.sa/guidelines/components/navigational/menu', '["استخدام القائمة كما هو معتمد دون تعديل على الشكل واللون والمسافات","تطبيق الحالات التفاعلية: Default, Hovered, Pressed, Focused, Disabled","تطبيق الحالات السياقية (Selected)"]', 'menu');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (17, 'P', 'عناصر', 'محول المحتوى يتبع نظام التصميم الموحد', 'Content switcher follows PC Design System', true, 'التأكد من استخدام مبدل المحتوى وفق نظام التصميم الموحد بحالاته المعتمدة', 'https://design.dga.gov.sa/guidelines/components/data-display/content-switcher', '["استخدام العنصر كما هو معتمد دون تعديل","تطبيق الحالات التفاعلية: Normal, Hovered, Focused","تطبيق الحالات السياقية: Selected"]', 'switcher');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (18, 'P', 'عناصر', 'الإشعارات تتبع نظام التصميم الموحد', 'Notifications follow PC Design System', true, 'ضمان التزام عنصر الإشعارات بمبادئ التصميم الموحد واستخدامه في سياقه الصحيح', 'https://design.dga.gov.sa/guidelines/components/feedback/notification', '["للإشعار المؤقت: استخدام Notification Toast","للإشعار الدائم: استخدام Inline Alert","للإشعار الدائم ذي الأولوية العالية في بداية الصفحة: استخدام Notification","استخدام الإشعارات في سياقها المحدد (نجاح، خطأ، تحذير...)"]', 'bell');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (19, 'P', 'عناصر', 'النوافذ المنبثقة تتبع النظام', 'Modals follow PC Design System', true, 'التأكد من توافق النوافذ المنبثقة مع إرشادات التصميم الموحد وسياق استخدامها الصحيح', 'https://design.dga.gov.sa/guidelines/components/feedback/modal', '["استخدام النافذة المنبثقة لمهام التأكيد والملاحظات والتنبيهات الهامة","عدم استخدام النوافذ المنبثقة لإدخال بيانات كبيرة — يُستخدم قالب النموذج بدلاً"]', 'modal');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (20, 'P', 'عناصر', 'رفع الملفات يتبع النظام', 'File upload follows PC Design System', true, 'التأكد من توافق عنصر رفع الملفات مع مبادئ التصميم الموحد بحالاته الكاملة', 'https://design.dga.gov.sa/guidelines/components/forms-and-inputs/file-uploader', '["تطبيق الحالات التفاعلية: Default, Drag + Hover, Disabled","تطبيق الحالات السياقية: Uploaded / Not Uploaded","عرض اسم الملف وحالته (جارٍ التحميل، مكتمل، فشل) والخيارات المصاحبة","رسائل توجيهية واضحة في حال فشل التحميل أو تجاوز الحجم"]', 'upload');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (21, 'P', 'عناصر', 'خانة الاختيار تتبع النظام', 'Checkbox follows PC Design System', true, 'ضمان أن عنصر مربع الاختيار يتبع النظام التصميمي الموحد بحالاته الكاملة', 'https://design.dga.gov.sa/guidelines/components/forms-and-inputs/checkbox', '["تطبيق الحالات التفاعلية: Default, Hovered, Focused, Read-only, Disabled","تطبيق الحالات السياقية: Checked / Unchecked / Indeterminate"]', 'checkbox');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (22, 'P', 'عناصر', 'زر الاختيار يتبع النظام', 'Radio follows PC Design System', true, 'ضمان أن عنصر زر الاختيار يتبع النظام التصميمي الموحد بحالاته الكاملة', 'https://design.dga.gov.sa/guidelines/components/forms-and-inputs/radio', '["تطبيق الحالات التفاعلية: Default, Hovered, Focused, Read-only, Disabled","تطبيق الحالات السياقية: Selected / Unselected"]', 'radio');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (23, 'P', 'عناصر', 'المفتاح يتبع نظام التصميم الموحد', 'Switch follows PC Design System', true, 'التأكد من أن عنصر زر التبديل يتماشى مع معايير التصميم الموحد', 'https://design.dga.gov.sa/guidelines/components/forms-and-inputs/switch', '["تطبيق الحالات التفاعلية: Default, Hovered, Focused, Disabled","تطبيق الحالات السياقية: On / Off"]', 'switch');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (24, 'P', 'عناصر', 'حقل النص الطويل يتبع النظام', 'Textarea follows PC Design System', true, 'التحقق من استخدام منطقة النص وفقاً لمبادئ التصميم الموحد بحالاتها الكاملة', 'https://design.dga.gov.sa/guidelines/components/forms-and-inputs/textarea', '["تطبيق الحالات التفاعلية: Default, Hovered, Pressed, Focused, Read-only, Disabled","دعم التلميحات (Placeholder) والنصوص المساعدة بشكل متناسق","وضوح رسائل الخطأ وطريقة معالجتها"]', 'textarea');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (25, 'P', 'عناصر', 'علامات التبويب تتبع النظام', 'Tabs follow PC Design System', true, 'ضمان أن علامات التبويب تتماشى مع إرشادات التصميم الموحد بوضوح بصري كامل', 'https://design.dga.gov.sa/guidelines/components/navigational/tabs', '["تطبيق الحالات التفاعلية: Default, Hovered, Focused, Disabled","تطبيق الحالات السياقية: Selected / Unselected","وضوح نص التبويب (الخط، الحجم، المحاذاة) مع التوازن البصري"]', 'tabs');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (26, 'P', 'عناصر', 'الوسوم تتبع نظام التصميم الموحد', 'Tags follow PC Design System', true, 'التأكد من أن عنصر العلامات يتبع النظام التصميمي مع الاستخدام الصحيح للألوان', 'https://design.dga.gov.sa/guidelines/components/search-and-filters/tags', '["للاستخدامات التنبيهية: استخدام الألوان التنبيهية المعتمدة حصراً","للاستخدامات العامة: استخدام ألوان محايدة أو أساسية","يُمنع استخدام الألوان التنبيهية لأغراض غير التنبيه"]', 'tag');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (27, 'P', 'عناصر', 'التذييل يتبع نظام التصميم الموحد', 'Footer follows PC Design System', true, 'ضمان استخدام عنصر التذييل مع احتوائه على جميع العناصر الإلزامية', 'https://design.dga.gov.sa/guidelines/components/ui-shell/footer', '["تصنيف الروابط في مجموعات ذات عناوين واضحة مثل \"روابط مهمة\" أو \"الدعم والمساعدة\"","احتواء التذييل على: الروابط الرسمية، الشعارات، معلومات التواصل، سياسات الخصوصية"]', 'footer');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (28, 'P', 'عناصر', 'البطاقات تتبع النظام', 'Cards follow PC Design System', true, 'التأكد من استخدام عنصر البطاقة وفقاً لمعايير التصميم الموحد بالتعديلات المسموحة فقط', 'https://design.dga.gov.sa/guidelines/components/content-display/card', '["تطبيق الحالات التفاعلية: Default, Hover, Focused, Disabled","التغييرات المسموحة فقط: تغيير المحاذاة الداخلية أو المسافات الداخلية","تطبيق متغيرات التصميم المحددة (بمحتوى، بصورة، بظل، بدون ظل...)","البطاقات القابلة للنقر يجب أن تحتوي على أزرار CTA"]', 'card');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (29, 'P', 'عناصر', 'شريط التنقل العلوي يتبع النظام', 'Nav Header follows PC Design System', true, 'التحقق من استخدام شريط التنقل العلوي وفقاً للمعايير مع استجابته لجميع الأجهزة', 'https://design.dga.gov.sa/guidelines/components/ui-shell/navigation-header', '["تطبيق الحالات التفاعلية للتبويبات والقوائم الفرعية","تطبيق الحالات السياقية (Selected)","استجابة شريط التنقل لجميع أحجام الشاشات والأجهزة","للتبويبات/القوائم الخارجية: إضافة أيقونة External link"]', 'nav');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (30, 'P', 'عناصر', 'مسار التنقل يتبع النظام', 'Breadcrumb follows PC Design System', true, 'التأكد من استخدام مسار التصفح وفق معايير التصميم الموحد مع اتساقه مع خريطة الموقع', 'https://design.dga.gov.sa/guidelines/components/navigational/breadcrumbs', '["تطبيق الحالات التفاعلية (الصفحة الحالية تكون Disabled وغير قابلة للنقر)","وضوح مسار التصفح وسهولة التفاعل معه على جميع الأجهزة","اتساق مسار التصفح مع التسلسل الهيكلي لخريطة الموقع"]', 'breadcrumb');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (31, 'P', 'عناصر', 'الصورة الرمزية تتبع النظام', 'Avatar follows PC Design System', true, 'التأكد من توافق عنصر الصورة الرمزية مع نظام التصميم الموحد بسياقاتها الثلاثة', 'https://design.dga.gov.sa/guidelines/components/data-display/avatar', '["الالتزام بأنواع السياقات الثلاثة: الحروف المختصرة، الصورة، الأيقونة"]', 'avatar');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (32, 'P', 'عناصر', 'التقييم يتبع النظام', 'Rating follows PC Design System', true, 'التحقق من استخدام عنصر التقييم وفق نظام التصميم الموحد بحالاته الكاملة', 'https://design.dga.gov.sa/guidelines/components/feedback/rating', '["تطبيق الحالات التفاعلية: Normal, Pressed","تطبيق الحالات السياقية: Selected, Half"]', 'star');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (33, 'P', 'عناصر', 'التلميح يتبع النظام', 'Tooltip follows PC Design System', true, 'التحقق من استخدام عنصر التلميح وفق نظام التصميم الموحد بموضعه المكاني الصحيح', 'https://design.dga.gov.sa/guidelines/components/feedback/tooltip', '["تطبيق موضع العنصر المكاني (أعلى، أسفل، يمين، يسار)","تطبيق المحاذاة (البداية، الوسط، النهاية) كما هو معتمد"]', 'tooltip');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (34, 'P', 'عناصر', 'حقل النص يتبع النظام', 'Text input follows PC Design System', true, 'التحقق من استخدام المدخلات وفق التصميم الموحد مع دعم كامل للتلميحات والأخطاء', 'https://design.dga.gov.sa/guidelines/components/forms-and-inputs/input', '["تطبيق الحالات: Default, Hovered, Pressed, Focused, Read-only, Disabled","دعم التلميحات (Placeholder) والنصوص المساعدة بشكل متناسق","وضوح رسائل الخطأ وطريقة معالجتها"]', 'input');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (35, 'P', 'عناصر', 'الجداول تتبع النظام', 'Tables follow PC Design System', true, 'التحقق من استخدام الجدول وفق نظام التصميم الموحد من حيث الشكل والألوان والمسافات', 'https://design.dga.gov.sa/guidelines/components/data-display/table', '["استخدام الجدول كما هو معتمد في كود المنصات من حيث الشكل واللون والمسافات"]', 'table');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (36, 'P', 'عناصر', 'منتقي التاريخ يتبع النظام', 'Date picker follows PC Design System', true, 'التحقق من استخدام محدد التاريخ وفق نظام التصميم الموحد بحالاته الكاملة', 'https://design.dga.gov.sa/guidelines/components/forms-and-inputs/datepicker', '["تطبيق الحالات التفاعلية: Default, Hovered, Pressed, Focused, Disabled","تطبيق الحالات السياقية: Selected, Today, Next/Prev"]', 'calendar');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (37, 'foundations', 'اساسيات', 'خريطة الموقع تدعم التنقل واكتشاف المحتوى', 'Sitemap supports navigation and discoverability', true, 'التأكد من التطبيق الصحيح للمعيار المذكور وفق قواعد كود المنصات.', 'https://design.dga.gov.sa/', '[]', 'chromeExt');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (44, 'S', 'عناصر', 'درج التنقل يتبع نظام التصميم الموحد', 'Nav Drawer follows PC Design System', true, 'التأكد من التطبيق الصحيح للمعيار المذكور وفق قواعد كود المنصات.', 'https://design.dga.gov.sa/', '[]', 'chromeExt');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (45, 'S', 'عناصر', 'ترقيم الصفحات يتبع النظام', 'Pagination follows PC Design System', true, 'التأكد من التطبيق الصحيح للمعيار المذكور وفق قواعد كود المنصات.', 'https://design.dga.gov.sa/', '[]', 'chromeExt');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (46, 'S', 'عناصر', 'مكون التحميل يتبع النظام', 'Loading component follows PC Design System', true, 'التأكد من التطبيق الصحيح للمعيار المذكور وفق قواعد كود المنصات.', 'https://design.dga.gov.sa/', '[]', 'chromeExt');
INSERT INTO public.extensions (num, pr, cat, t_ar, t_en, ref, desc_text, link, subs, icon) VALUES (47, 'S', 'عناصر', 'مكون الخطوات يتبع النظام', 'Steps component follows PC Design System', true, 'التأكد من التطبيق الصحيح للمعيار المذكور وفق قواعد كود المنصات.', 'https://design.dga.gov.sa/', '[]', 'chromeExt');
